[tox]
envlist =
  py3{10,11,12,13,14,15}-lint,
  py3{10,11,12,13,14,15}-unit,
  py3{10,11,12,13,14,15}-bandit,
  py3{10,11,12,13,14,15}-mypy,
  py314-lint-readme,
  py314-pydocstyle
isolated_build = True
skip_missing_interpreters = True

[gh-actions]
python =
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314
  3.14: py315

[testenv]
description =
  py3{10,11,12,13,14,15}-unit: Run the unit tests
  py3{10,11,12,13,14,15}-lint: Lint the Python code
  py3{10,11,12,13,14,15}-bandit: Search for common security issues
  py3{10,11,12,13,14,15}-mypy: Check for type safety
  py314-pydocstyle: docstring style checker
  py314-lint-readme: Lint the README.rst->.md conversion

passenv =
  CI
  GITHUB_*
deps =
  py3{10,11,12,13,14,15}-lint: -rlint-requirements.txt
  py3{10,11,12,13,14,15}-bandit: bandit[toml]
  py3{10,11,12,13,14,15}-mypy: -rmypy-requirements.txt

setenv =
  py3{10,11,12,13,14,15}-unit: LC_ALL = C.UTF-8

commands =
  py3{10,11,12,13,14,15}-unit: python -m pip install -U pip setuptools wheel
  py3{10,11,12,13,14,15}-unit: make coverage-report coverage.xml PYTEST_EXTRA={posargs}
  py3{10,11,12,13,14,15}-bandit: bandit --configfile pyproject.toml --recursive src/cwl_utils
  py3{10,11,12,13,14,15}-lint: make flake8
  py3{10,11,12,13,14,15}-lint: make format-check
  py3{10,11,12,13,14,15}-mypy: make mypy

allowlist_externals =
  py3{10,11,12,13,14,15}-lint: flake8
  py3{10,11,12,13,14,15}-lint: black
  py3{10,11,12,13,14,15}-{mypy,shellcheck,lint,unit}: make

skip_install =
  py3{10,11,12,13,14,15}-lint: true
  py3{10,11,12,13,14,15}-bandit: true

extras =
  py3{10,11,12,13,14,15}-mypy: testing
  py3{10,11,12,13,14,15}-unit: pretty, testing

[testenv:py314-pydocstyle]
allowlist_externals = make
commands = make pydocstyle
deps =
    ruff
skip_install = true

[testenv:py314-lint-readme]
description = Lint the README.rst->.md conversion
commands =
  make clean dist
  twine check dist/cwl[-_]utils*
deps =
    twine
    build
    readme_renderer[rst]
skip_install = true
