name: Publish tag to PyPI

on:
  push:
    tags: [ 'v*' ]

concurrency:
  group: tag-${{github.ref}}
  cancel-in-progress: true

jobs:
  release_to_pypi:
    name: cwl-utils release test
    runs-on: ubuntu-24.04
    environment: PyPI
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Singularity
        run: |
          wget --no-verbose https://github.com/sylabs/singularity/releases/download/v4.2.1/singularity-ce_4.2.1-noble_amd64.deb
          sudo apt-get install -y ./singularity-ce_4.2.1-noble_amd64.deb

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.12

      - name: Install packages
        run: |
          pip install -U pip setuptools wheel
          pip install virtualenv

      - name: Release test
        env:
          RELEASE_SKIP: head
        run: ./release-test.sh

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          packages-dir: testenv2/src/cwl-utils/dist/
